# Generated by Django 4.2.3 on 2023-07-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='api_data',
            fields=[
                ('E_ID', models.AutoField(primary_key=True, serialize=False)),
                ('OLT_Hostname', models.CharField(max_length=50)),
                ('Branch_name', models.CharField(max_length=100)),
                ('Interface', models.CharField(max_length=50)),
                ('Pon_port', models.CharField(max_length=50)),
                ('ONU_Serial_number', models.CharField(max_length=50)),
                ('User_Description', models.CharField(max_length=50)),
                ('Last_Update', models.CharField(max_length=50)),
                ('Remarks', models.CharField(max_length=255)),
            ],
        ),
    ]
