# Generated by Django 4.2.3 on 2023-07-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_api_data_admin_status_api_data_host_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='api_data',
            options={'ordering': ['E_ID', 'OLT_Hostname', 'Branch_name', 'Interface', 'Pon_port', 'ONU_Serial_number', 'User_Description', 'Admin_Status', 'Operational_Status', 'PON_Admin_Status', 'PON_Opertional_Status', 'Last_Update', 'Host_Status', 'Uptime', 'Downtime', 'acknowledged_status', 'Remarks'], 'verbose_name_plural': 'API Data'},
        ),
        migrations.AddField(
            model_name='api_data',
            name='Downtime',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='api_data',
            name='Uptime',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='api_data',
            name='acknowledged_status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
