# Generated by Django 4.2.3 on 2023-07-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_api_data_options_api_data_downtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_data',
            name='Admin_Status',
            field=models.CharField(blank=True, choices=[('1', 'UP'), ('2', 'DOWN'), ('True', 'UP'), ('False', 'Down')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='api_data',
            name='Host_Status',
            field=models.CharField(blank=True, choices=[('1', 'UP'), ('2', 'DOWN'), ('True', 'UP'), ('False', 'Down')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='api_data',
            name='Operational_Status',
            field=models.CharField(blank=True, choices=[('1', 'UP'), ('2', 'DOWN'), ('True', 'UP'), ('False', 'Down')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='api_data',
            name='PON_Admin_Status',
            field=models.CharField(blank=True, choices=[('1', 'UP'), ('2', 'DOWN'), ('True', 'UP'), ('False', 'Down')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='api_data',
            name='PON_Opertional_Status',
            field=models.CharField(blank=True, choices=[('1', 'UP'), ('2', 'DOWN'), ('True', 'UP'), ('False', 'Down')], max_length=50, null=True),
        ),
    ]
