# Generated by Django 4.2.3 on 2023-07-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_api_data_admin_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_data',
            name='Customer_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
