# Generated by Django 4.2.3 on 2023-07-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_api_data_customer_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='api_data',
            options={'ordering': ['E_ID', 'OLT_Hostname', 'Branch_name', 'Interface', 'Pon_port', 'Onu_id', 'ONU_Serial_number', 'User_Description', 'Admin_Status', 'Operational_Status', 'PON_Admin_Status', 'PON_Opertional_Status', 'Last_Update', 'Host_Status', 'Uptime', 'Downtime', 'acknowledged_status', 'Remarks'], 'verbose_name_plural': 'API Data'},
        ),
        migrations.AddField(
            model_name='api_data',
            name='Onu_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='api_data',
            name='Admin_Status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='api_data',
            name='Host_Status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='api_data',
            name='Operational_Status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='api_data',
            name='PON_Admin_Status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='api_data',
            name='PON_Opertional_Status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='api_data',
            name='acknowledged_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
